python l-autoGaz1.py
python l-autoGaz2.py
python l-autoGaz3.py
python l-autoGaz4.py
python l-autoGaz5.py
python l-autoGaz6.py
python l-autoGaz7.py
python l-autoGaz8.py
python l-autoGaz9.py
python l-autoGaz10.py
python l-autoGaz11.py
python l-autoGaz12.py
python l-autoGaz13.py
python l-autoGaz14.py
python l-autoGaz15.py
python l-autoGaz16.py
python l-autoGaz17.py